name: Setup HLF
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hyperledger Fabric
        uses: arjundashrath/setup-hlf@v0.0.1
        with:
          fabric-version: 2.2.2
